### ISSUE TITLE
Please remove scroll horizontal in home

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/blanja-fe#7]
![Screenshot (161)](https://github.com/IrhamNfrnda/blanja-fe/assets/49361887/c1a98ffc-bee3-4c76-93b9-2c107e787015)

**Comment by nluthfis** [comment]
![image](https://github.com/IrhamNfrnda/blanja-fe/assets/42950482/27f7d593-9c7d-40c2-b17f-edc05e0d672e)
Fixed!
